import { PublicLayout } from '@/components/layout/public-layout';

export default function TermsPage() {
  return (
    <PublicLayout>
      <section className="px-4 sm:px-6 lg:px-8 py-16 sm:py-24">
        <div className="max-w-3xl mx-auto">
          <h1 className="text-3xl sm:text-4xl font-bold mb-2">Terms of Service</h1>
          <p className="text-muted-foreground mb-10">Last updated: April 6, 2026</p>

          <div className="space-y-8">
            <section>
              <h2 className="text-xl font-bold mb-3">1. Acceptance of Terms</h2>
              <p className="text-muted-foreground leading-relaxed text-sm">
                By accessing or using BrainBoost (&quot;the Service&quot;), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold mb-3">2. Description of Service</h2>
              <p className="text-muted-foreground leading-relaxed text-sm">
                BrainBoost is an AI-powered study platform that allows users to upload study materials and generate flashcards, quizzes, summaries, and personalized study schedules. The Service uses AI technology to process and analyze uploaded content.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold mb-3">3. User Accounts</h2>
              <ul className="list-disc list-inside space-y-1.5 text-muted-foreground text-sm">
                <li>You must provide accurate and complete information when creating an account.</li>
                <li>You are responsible for maintaining the security of your account credentials.</li>
                <li>You must be at least 13 years old to use the Service.</li>
                <li>One person may not maintain more than one free account.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-bold mb-3">4. Content Ownership</h2>
              <p className="text-muted-foreground leading-relaxed text-sm">
                You retain full ownership of all study materials you upload to BrainBoost. By uploading content, you grant us a limited license to process it through our AI systems solely for the purpose of providing study features. We do not claim ownership of your content and will not use it for any other purpose.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold mb-3">5. Acceptable Use</h2>
              <p className="text-muted-foreground leading-relaxed text-sm mb-3">You agree not to:</p>
              <ul className="list-disc list-inside space-y-1.5 text-muted-foreground text-sm">
                <li>Upload content that infringes on intellectual property rights of others.</li>
                <li>Use the Service for any illegal or unauthorized purpose.</li>
                <li>Attempt to reverse-engineer, decompile, or hack the Service.</li>
                <li>Share your account credentials with others or use another user&apos;s account.</li>
                <li>Upload malicious files or content designed to harm the Service.</li>
                <li>Use automated systems to access the Service beyond normal use.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-bold mb-3">6. Subscriptions & Payments</h2>
              <ul className="list-disc list-inside space-y-1.5 text-muted-foreground text-sm">
                <li>Free accounts are subject to usage limits as described on the pricing page.</li>
                <li>Pro and Teams subscriptions are billed monthly via Stripe.</li>
                <li>You may cancel your subscription at any time; access continues until the end of the billing period.</li>
                <li>Refunds are available within 7 days of initial purchase if you&apos;re unsatisfied.</li>
                <li>We reserve the right to change pricing with 30 days notice to existing subscribers.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-bold mb-3">7. AI-Generated Content</h2>
              <p className="text-muted-foreground leading-relaxed text-sm">
                Flashcards, quizzes, summaries, and AI tutor responses are generated by artificial intelligence and may contain errors. You are responsible for reviewing AI-generated content for accuracy. BrainBoost does not guarantee the correctness of AI-generated study materials.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold mb-3">8. Limitation of Liability</h2>
              <p className="text-muted-foreground leading-relaxed text-sm">
                BrainBoost is provided &quot;as is&quot; without warranties of any kind. We are not liable for any academic outcomes, exam results, or damages arising from the use of our Service. Our total liability shall not exceed the amount you paid for the Service in the 12 months preceding the claim.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold mb-3">9. Termination</h2>
              <p className="text-muted-foreground leading-relaxed text-sm">
                We may suspend or terminate your account if you violate these terms. You may delete your account at any time from your profile settings. Upon termination, your data will be deleted within 30 days.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold mb-3">10. Changes to Terms</h2>
              <p className="text-muted-foreground leading-relaxed text-sm">
                We may update these terms from time to time. We&apos;ll notify you of material changes via email. Continued use of the Service after changes constitutes acceptance of the new terms.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold mb-3">11. Contact</h2>
              <p className="text-muted-foreground leading-relaxed text-sm">
                For questions about these Terms, contact us at{' '}
                <a href="mailto:legal@brainboost.app" className="text-primary hover:underline">legal@brainboost.app</a>.
              </p>
            </section>
          </div>
        </div>
      </section>
    </PublicLayout>
  );
}
